#! /bin/sh

ETH="p33p1"
SRC="193.168.15.25"

case $1 in
start)
	echo 1 > /proc/sys/net/ipv4/ip_forward
	/sbin/iptables -F
	/sbin/iptables -P INPUT ACCEPT
	/sbin/iptables -P FORWARD ACCEPT
	/sbin/iptables -t nat -A POSTROUTING -o $ETH -s $SRC -j MASQUERADE
;;
stop)
	echo 0 > /proc/sys/net/ipv4/ip_forward
;;
*)
	echo $"Usage: $0 {start|stop}";
esac
